name: portfolio
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_pdfview: ^1.3.3
  path_provider: ^2.0.11
  pdf_render: ^1.4.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
  - assets/
  - assets/sample1.pdf
  - assets/sample2.pdf
  - assets/sample3.pdf
  - assets/sample4.pdf
  - assets/test2.pdf

